networks:
  front_general:
  front_evil:
  backend:

services:
  front_general:
    image: nginx:1.31.1-alpine3.23-slim
    volumes:
      - ./nginx/front-general.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./general-website/frontend:/data:ro
    networks:
      - front_general


  backend:
    build:
      context: ./general-website/backend/
    networks:
      - backend


  front_evil:
    image: nginx:1.31.1-alpine3.23-slim
    volumes:
      - ./nginx/front-evil.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./evil-website:/data:ro
    networks:
      - front_evil


  reverse_proxy:
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    ports:
      - 127.0.0.1:443:443/tcp
    volumes:
      - ./nginx/reverse-proxy.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - front_general
      - backend
      - front_evil


  unbound_dns:
    image: mvance/unbound:1.21.1

    ports:
      - 127.0.0.1:53:53/udp

    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro

